apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
data:
  DB_HOST: mongo-service
  DB_PORT: "27017"
  PORT: "5001"
  MONGODB_URI: "mongodb://admin:password@mongo-service:27017/chatApp?authSource=admin&retryWrites=true&w=majority"
  JWT_SECRET: "your_jwt_secret_key"
  NODE_ENV: "production"